# =============================================================================
# Makefile: development tasks for Unbihexium
# =============================================================================
#
# Run `make` or `make help` to list every target with its description.
#
# Requirements
#   - Python 3.10 to 3.14 (the interpreter on PATH, or set PYTHON=...)
#   - uv (https://docs.astral.sh/uv/) for `make lock` and `make lock-check`
#   - Docker for the docker-* targets
#   - Node.js (npx) for `make md-lint`
#
# Variables can be overridden on the command line, for example:
#   make test PYTHON=python3.13
#   make docker-build IMAGE=unbihexium:dev
#
# Targets mirror the checks in .github/workflows/ so that contributors can
# reproduce CI results locally before opening a pull request.
# =============================================================================

.DEFAULT_GOAL := help
SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

PYTHON ?= python
PIP ?= $(PYTHON) -m pip
UV ?= uv
IMAGE ?= unbihexium:local
SRC := src/unbihexium
PORT ?= 8000

LOCK_PYTHON := 3.10
LOCK_FLAGS := --universal --python-version $(LOCK_PYTHON)

.PHONY: help install install-dev lock lock-check test test-fast test-cov \
        lint format format-check type-check security licence text-policy \
        yaml-lint md-lint notebooks model-zoo check pre-commit build check-dist docker-build docker-run docker-api \
        validate verify clean distclean

##@ Help

help: ## Show this help
	@awk 'BEGIN {FS = ":.*## "} \
		/^##@ / {printf "\n%s\n", substr($$0, 5); next} \
		/^[a-zA-Z0-9_-]+:.*## / {printf "  %-16s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

##@ Installation

install: ## Install the package with the locked runtime dependencies
	$(PIP) install -r requirements.txt
	$(PIP) install --no-deps .

install-dev: ## Install the locked development environment and pre-commit hooks
	$(PIP) install -r requirements-dev.txt
	$(PIP) install --no-deps -e .
	pre-commit install

lock: ## Regenerate requirements.txt and requirements-dev.txt from pyproject.toml
	$(UV) pip compile pyproject.toml $(LOCK_FLAGS) --extra onnx --extra serving \
		--custom-compile-command "uv pip compile pyproject.toml $(LOCK_FLAGS) --extra onnx --extra serving -o requirements.txt" \
		-o .requirements.lock.tmp
	$(UV) pip compile pyproject.toml $(LOCK_FLAGS) --extra all \
		--custom-compile-command "uv pip compile pyproject.toml $(LOCK_FLAGS) --extra all -o requirements-dev.txt" \
		-o .requirements-dev.lock.tmp
	@$(PYTHON) -c "import pathlib, re; \
	[pathlib.Path(out).write_text(re.split(r'(?m)^# This file was autogenerated by uv', pathlib.Path(out).read_text(), maxsplit=1)[0] + pathlib.Path(tmp).read_text()) \
	 for out, tmp in (('requirements.txt', '.requirements.lock.tmp'), ('requirements-dev.txt', '.requirements-dev.lock.tmp'))]"
	@rm -f .requirements.lock.tmp .requirements-dev.lock.tmp
	@echo "Lock files regenerated. Review the diff before committing."

lock-check: ## Fail if the lock files are out of date with pyproject.toml
	@cp requirements.txt .requirements.orig && cp requirements-dev.txt .requirements-dev.orig
	@$(MAKE) --no-print-directory lock > /dev/null
	@status=0; \
	cmp -s requirements.txt .requirements.orig || status=1; \
	cmp -s requirements-dev.txt .requirements-dev.orig || status=1; \
	mv .requirements.orig requirements.txt; mv .requirements-dev.orig requirements-dev.txt; \
	if [ $$status -ne 0 ]; then echo "Lock files are outdated: run make lock"; exit 1; fi; \
	echo "Lock files are up to date."

##@ Tests

test: ## Run the complete test suite
	$(PYTHON) -m pytest tests/

test-fast: ## Run unit tests in parallel, skipping slow and GPU tests
	$(PYTHON) -m pytest tests/unit -n auto -m "not slow and not gpu"

test-cov: ## Run the test suite with branch coverage (terminal and XML report)
	$(PYTHON) -m pytest tests/ --cov=$(SRC) --cov-report=term-missing --cov-report=xml

##@ Code quality

lint: ## Lint the code with ruff
	ruff check src/ tests/

format: ## Format the code with ruff and apply safe lint fixes
	ruff format src/ tests/
	ruff check --fix src/ tests/

format-check: ## Check formatting without changing files
	ruff format --check src/ tests/

type-check: ## Type check the package with pyright
	pyright src/

security: ## Run bandit and pip-audit
	bandit -c pyproject.toml -r src/
	pip-audit -r requirements.txt --no-deps --disable-pip --progress-spinner off
	pip-audit -r requirements-dev.txt --no-deps --disable-pip --progress-spinner off

licence: ## Check REUSE compliance and the MPL-2.0 notices
	@# reuse runs in the isolated pre-commit environment, which also copies
	@# LICENSE.txt to the git-ignored LICENSES/MPL-2.0.txt that REUSE expects.
	pre-commit run reuse-lint-file --all-files
	$(PYTHON) .github/scripts/check_license_headers.py

text-policy: ## Check for emojis, em dashes and non-English letters
	$(PYTHON) .github/scripts/check_text_policy.py

yaml-lint: ## Lint all YAML files with yamllint
	pre-commit run yamllint --all-files

md-lint: ## Lint all Markdown files with markdownlint
	npx --yes markdownlint-cli@0.49.1 --config .markdownlint.yaml "**/*.md" --ignore node_modules

notebooks: ## Validate the example notebooks (format, no outputs)
	$(PYTHON) .github/scripts/check_notebooks.py examples/notebooks

model-zoo: ## Check model zoo structure, checksums, cards and manifests
	$(PYTHON) .github/scripts/check_model_zoo.py

check: lint format-check type-check test licence text-policy yaml-lint notebooks model-zoo ## Run all local checks that CI runs

pre-commit: ## Run every pre-commit hook on all files
	pre-commit run --all-files

##@ Packaging and containers

build: ## Build the sdist and wheel into dist/
	$(PYTHON) -m build

check-dist: build ## Build and validate the distributions with twine
	$(PYTHON) -m twine check --strict dist/*

docker-build: ## Build the container image
	docker build \
		--build-arg VERSION="$$($(PYTHON) -c 'import tomllib; print(tomllib.load(open("pyproject.toml", "rb"))["project"]["version"])')" \
		--build-arg VCS_REF="$$(git rev-parse HEAD)" \
		--build-arg BUILD_DATE="$$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
		-t $(IMAGE) .

docker-run: ## Run the command line interface in the container
	docker run --rm $(IMAGE) unbihexium --help

docker-api: ## Run the REST API in the container on http://localhost:$(PORT)
	docker run --rm -p $(PORT):8000 $(IMAGE) \
		uvicorn unbihexium.serving.app:app --host 0.0.0.0 --port 8000

##@ Model zoo and verification

validate: ## Load and run every model (requires Git LFS weights)
	$(PYTHON) scripts/validate_models.py

verify: ## Print the installed version and the number of registered models
	$(PYTHON) -c "import unbihexium; print(f'Version: {unbihexium.__version__}')"
	$(PYTHON) -c "from unbihexium.zoo import list_models; print(f'Models: {len(list_models())}')"

##@ Cleaning

clean: ## Remove build artefacts and caches
	rm -rf build/ dist/ site/ *.egg-info .pytest_cache .ruff_cache .mypy_cache .coverage coverage.xml htmlcov/
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	find . -type f -name "*.py[co]" -delete

distclean: clean ## Also remove virtual environments and tox environments
	rm -rf .venv/ venv/ .tox/ .nox/
