name: Feature Request
description: Suggest a new feature for unbihexium
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you have considered.

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Which domain does this feature relate to?
      options:
        - Core
        - AI/Detection
        - Indices
        - Geostatistics
        - Analysis
        - Model Zoo
        - CLI
        - Documentation
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots.
