# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# =============================================================================
# Project     : Unbihexium
# Module      : scripts/merge_lock.py
# Title       : Merge fresh uv output into the commented lock files
# Author      : Olaf Yunus Laitinen Imanov <yunus.z.imanov@helsinki.fi>
# Affiliation : University of Helsinki
# Copyright   : 2025-2026 Unbihexium OSS Foundation and contributors
# Licence     : Mozilla Public License 2.0, see LICENSE.txt
# Python      : CPython 3.10 to 3.14, standard library only
# =============================================================================
#
# Abstract
# --------
# Used by `make lock`. The lock files requirements.txt and requirements-dev.txt
# consist of three parts:
#
#   header     the hand-written licence notice, header block and abstract,
#              everything before the line "# This file was autogenerated by
#              uv"
#   body       the output of `uv pip compile`, which starts with that line
#   footer     the hand-written closing block, from the "# ====" line just
#              before "# End of file" to the end of the file
#
# For each pair of paths the script keeps the header and the footer of the
# existing lock file and replaces the body with the fresh uv output read from
# the temporary file. A lock file without a footer gets none. Running the
# script twice with the same uv output gives the same file.
#
# Usage
# -----
#   python scripts/merge_lock.py LOCK_FILE UV_OUTPUT [LOCK_FILE UV_OUTPUT ...]
#
# Exit status
# -----------
#   0  every lock file was written
#   2  the arguments are not pairs of paths
# =============================================================================

# Postpone the evaluation of annotations so that modern type syntax works on
# every supported Python version.
from __future__ import annotations

# Find the boundaries between header, body and footer.
import re

# Access the command line arguments and set the exit status.
import sys

# Represent file paths.
from pathlib import Path

# First line of the uv output; the header ends before it.
BODY_START = re.compile(r"^# This file was autogenerated by uv", re.MULTILINE)

# Opening rule of the footer followed by its "End of file" line.
FOOTER_START = re.compile(r"^# =+\n# End of file ", re.MULTILINE)


# Split a lock file into its hand-written header and footer.
def header_and_footer(text: str) -> tuple[str, str]:
    # Position of the uv output, if the file has one.
    body = BODY_START.search(text)
    # Without uv output the whole file is the header.
    header = text[: body.start()] if body else text
    # Footers after the start of the uv output.
    footers = list(FOOTER_START.finditer(text, body.start() if body else len(text)))
    # The last match is the footer; there is none without a match.
    footer = text[footers[-1].start() :] if footers else ""
    # Both hand-written parts.
    return header, footer


# Merge the fresh uv output into one lock file.
def merge(lock_file: Path, uv_output: Path) -> None:
    # Hand-written parts of the existing lock file.
    header, footer = header_and_footer(lock_file.read_text(encoding="utf-8"))
    # Fresh uv output, ending with exactly one newline.
    body = uv_output.read_text(encoding="utf-8").rstrip("\n") + "\n"
    # A blank line separates the uv output from the footer.
    tail = "\n" + footer if footer else ""
    # Write the merged lock file.
    lock_file.write_text(header + body + tail, encoding="utf-8")


# Merge every pair of paths given on the command line.
def main(argv: list[str]) -> int:
    # The arguments must form pairs of lock file and uv output.
    if not argv or len(argv) % 2:
        # Explain the usage.
        print("usage: merge_lock.py LOCK_FILE UV_OUTPUT [LOCK_FILE UV_OUTPUT ...]", file=sys.stderr)
        # Usage error.
        return 2
    # Walk over the pairs.
    for lock_file, uv_output in zip(argv[::2], argv[1::2], strict=True):
        # Merge one lock file.
        merge(Path(lock_file), Path(uv_output))
    # Success.
    return 0


# Run the merge when the file is executed as a script.
if __name__ == "__main__":
    # Pass the command line arguments without the script name.
    sys.exit(main(sys.argv[1:]))

# =============================================================================
# End of module scripts/merge_lock.py
# Part of Unbihexium (https://github.com/unbihexium-oss/unbihexium).
# Cite the project as described in CITATION.cff.
# =============================================================================
